[package]
name = "rsvg"
version = "0.4.0"
authors = ["selaux"]
description = "Rust bindings for the Rsvg library"
repository = "https://github.com/selaux/rsvg-rs"
license = "MIT"

keywords = ["rsvg", "svg", "gtk-rs"]
include = ["src/**/*", "Cargo.toml"]

[lib]
name = "rsvg"

[dependencies]
libc = "0.2"
bitflags = "1.0"
glib = "0.6.0"
glib-sys = "0.7.0"
gobject-sys = "0.7.0"
gdk-pixbuf = "0.5.0"

[dev-dependencies]
image = "0.18.0"
imageproc = "0.14.0"
gtk = "0.5.0"

[dependencies.cairo-rs]
version = "0.5.0"
features = ["png"]

[dependencies.rsvg-sys]
version = "0.6.0"
path = "./rsvg-sys"
